extends "res://tests/phase_5b_smoke.gd"
func run()->void:
	var state:=preload("res://tests/fixtures/museum_management_fixture.gd").state_with_displays(50)
	var store:=MuseumProfileStore.in_memory();check(store.save_profile(state),"V10 pure value state saves")
	var loaded:=store.load_profile()
	check(not store.write_blocked and store.encode(loaded)==store.encode(state),"V10 exact collection/achievement/finance roundtrip")
	var awards:=loaded.achievements.duplicate(true);store.load_profile();MuseumCollectionCodex.rows(loaded)
	check(loaded.achievements==awards,"Reload and viewing do not reaward honors")
	var old:=store.encode(state);old.version=9;old.erase("reputation_version");old.erase("collection_history");old.erase("museum_achievements")
	var disk:=MuseumProfileStore.new();disk.save_path="res://logs/11h_v9_%d.json"%Time.get_ticks_usec()
	var f:=FileAccess.open(disk.save_path,FileAccess.WRITE);f.store_string(JSON.stringify(old));f.close()
	var sha:=FileAccess.get_sha256(disk.save_path);var migrated:=disk.load_profile()
	check(not disk.write_blocked and migrated.cash==state.cash and migrated.collection.all_items().size()==50 and migrated.display_assignments==state.display_assignments,"V9 migration keeps assets and placements")
	check(migrated.achievements.is_empty() and migrated.collection_history.ly_attendant.identified_day==0,"Migration computes current evidence but never invents completed honors/dates")
	check(disk.save_profile(migrated) and FileAccess.get_sha256("%s.v9.%s.backup.json"%[disk.save_path,sha.substr(0,12)])==sha,"V10 writes exact V9 source backup")
	var bad:=store.encode(state);bad.collection_history["RESEARCH_INDEX_1"]={};store.decode(bad)
	check(store.write_blocked,"Research index cannot become collectible progress")
	bad=store.encode(state);bad.museum_achievements.FIRST_ACCESSION.day_number=state.day_number+1;store.decode(bad)
	check(store.write_blocked,"Future honor date protects original")
	bad=store.encode(state);bad.collection_history.ly_attendant.regions=["INVENTED"];store.decode(bad)
	check(store.write_blocked,"Invalid expedition region cannot be saved")
	var guard:=MuseumProfileStore.new();guard.save_path=disk.save_path;guard.load_profile();f=FileAccess.open(guard.save_path,FileAccess.WRITE);f.store_string("external change");f.close()
	check(not guard.save_profile(state) and FileAccess.get_file_as_string(guard.save_path)=="external change","External conflict never overwritten")
	for count in [50,100,500]:
		var fixture:=preload("res://tests/fixtures/museum_management_fixture.gd").state_with_displays(count)
		var museum:=Museum.new();museum.state=fixture;museum.config=MuseumConfig.new();root.add_child(museum);await frames(3)
		var start:=Time.get_ticks_usec()
		museum.reputation_panel.open(1)
		print("[11H performance] %d owned / open-refresh %.2f ms / visible rows %d"%[count,(Time.get_ticks_usec()-start)/1000.0,museum.reputation_panel.catalog_list.item_count])
		check(museum.reputation_panel.catalog_list.item_count<=20 and museum.reputation_panel.rows.size()==50,"Bounded real collection UI at %d owned instances"%count)
		var snapshot:=fixture.achievements.duplicate(true);museum.reputation_panel.refresh()
		check(fixture.achievements==snapshot,"UI refresh read-only at %d"%count)
		museum.reputation_panel.status.select(1);museum.reputation_panel.status.item_selected.emit(1)
		check(museum.reputation_panel.rows.all(func(row:Dictionary)->bool:return not row.discovered),"Unknown filter only shows undiscovered definitions")
		museum.reputation_panel.status.select(5);museum.reputation_panel.status.item_selected.emit(5)
		check(museum.reputation_panel.rows.all(func(row:Dictionary)->bool:return row.owned>0),"Owned filter uses actual current instance counts")
		museum.reputation_panel.region.select(2);museum.reputation_panel.region.item_selected.emit(2)
		check(museum.reputation_panel.rows.is_empty(),"Region UI never infers provenance from fixture names")
		museum.queue_free();await frames(3)
	print("[11H4] %d checks, %d failures"%[checks,failures]);quit(0 if failures==0 else 1)
