extends "res://tests/phase_7b_smoke.gd"
const FLOW_SCENE:=preload("res://scenes/main/game_flow.tscn")
func run()->void:
 var state:=MuseumState.new()
 state.campaign_seed=52
 state.museum_level=2
 state.day_number=9
 state.cash=1234
 var ids:Array[StringName]=[]
 for def in preload("res://data/antiques/formal_pool.tres").antiques:ids.append(state.collection.add(def.id,3,91,true).instance_id)
 var slots:=state.display_catalog.units[&"CASE_2"].slots()
 for i in range(8):check(state.place(slots[i].id,ids[i]),"standard unit accepts unique instance "+str(i))
 check(state.unit_items(&"CASE_2").size()==8,"one unit has eight")
 check(not state.place(&"CASE_1",ids[0]),"same instance cannot cross units")
 check(not state.place(&"CASE_2/09",ids[0]),"nonexistent overcapacity slot rejected")
 var preserved:=state.display_assignments.duplicate()
 state.place(slots[0].id,ids[0])
 check(state.display_assignments==preserved,"repeated placement is unique, never duplicated")
 var unknown_profile:Dictionary=state.display_catalog.profiles[str(MuseumState.POOL.antiques[0].id)].duplicate(true)
 unknown_profile.erase("size_cm")
 check(not state.display_catalog.accepts(state.display_catalog.units[&"CASE_2"],unknown_profile),"unknown dimensions cannot use standard case")
 var painting:={"category":"PAINTING","size_cm":[80,4,100],"transport":"HAND_CARRY"}
 check(state.display_catalog.accepts(state.display_catalog.units[&"WALL_E1"],painting),"wall supports matching painting footprint as a planning rule")
 check(not state.display_catalog.accepts(state.display_catalog.units[&"CASE_2"],painting),"painting does not enter ordinary cabinet")
 check(state.display_catalog.units[&"PLATFORM_W1"].capacity==1,"large platform capacity one")
 var locked:=state.collection.add(&"republic_silver_coin",3,100,true)
 check(state.consign(locked.instance_id,2) and not state.place(&"CASE_1",locked.instance_id),"pending auction cannot display")
 var un:=state.collection.add(&"blue_white_jar",3,43,false)
 check(not state.place(&"CASE_1",un.instance_id),"unidentified cannot display")
 check(not state.display_catalog.accepts(state.display_catalog.units[&"CASE_2"],{"category":"COIN","transport":"HAND_CARRY"}),"unknown size rejected")
 check(not state.place(&"WALL_E1/01",un.instance_id),"painting wall does not accept pottery")
 check(not state.display_catalog.accepts(state.display_catalog.units[&"PLATFORM_W1"],{"category":"LARGE_FOSSIL","size_cm":[200,100,200],"transport":"EXPEDITION_TRANSPORT"}),"large fossil has no legal transport")
 var store:=MuseumProfileStore.in_memory()
 var payload:=store.encode(state)
 var decoded:=store.decode(payload)
 check(store.encode(decoded)==payload,"v5 multi-slot roundtrip")
 # Build genuine legacy assignments: one first-position in each CASE_n.
 state.withdraw_unit(&"CASE_2")
 for i in range(8):check(state.assign(StringName("CASE_%d"%(i+1)),ids[i]),"legacy assignment "+str(i))
 payload=store.encode(state);payload.version=4;payload.erase("display_layout_version")
 decoded=store.decode(payload)
 check(decoded.display_assignments==state.display_assignments and decoded.cash==1234 and decoded.day_number==9 and decoded.auction_lot_instance_id==locked.instance_id,"v4 migration retains money/date/auction/display")
 for id in ids:check(decoded.collection.find(id).condition==91 and decoded.collection.find(id).identified,"v4 condition and identity retained")
 var flow:=FLOW_SCENE.instantiate() as GameFlow
 flow.profile_store=MuseumProfileStore.in_memory()
 root.add_child(flow)
 await frames(3)
 var museum:=flow.museum
 for def in preload("res://data/antiques/formal_pool.tres").antiques:flow.museum_state.collection.add(def.id,1,100,true)
 museum.collection_panel.open(&"CASE_2")
 check(museum.collection_panel.slot_list.item_count==8,"manager shows eight slots")
 check(flow.museum_state.fill_unit(&"CASE_2",museum.collection_panel.filtered_ids)==8,"filtered batch fills eight")
 museum.collection_panel.refresh_slots()
 await frames(2)
 museum.collection_panel.close()
 check(museum.cases.size()==3 and museum.active_hall_id==&"MAIN","only current hall units instantiated")
 museum.switch_hall(&"EAST")
 await frames(3)
 check(museum.cases.size()==1 and museum.cases[0].case_id==&"COIN_E1","east hall only coin display instantiated")
 museum.switch_hall(&"MAIN")
 await frames(3)
 check(museum.cases.size()==3 and flow.museum_state.unit_items(&"CASE_2").size()==8,"return restores display without duplicating items")
 flow.queue_free();await frames(3)
 await preload("res://tests/phase_10d6_migration_checks.gd").new(self).run()
 await preload("res://tests/phase_10d6_integration_checks.gd").new(self).run()
 print("Phase 10D6: %d checks, %d failures"%[checks,failures])
 quit(1 if failures else 0)
