extends "res://tests/phase_5b_smoke.gd"
func run()->void:
	var state:=MuseumState.new()
	var museum:=Museum.new()
	museum.state=state
	museum.config=MuseumConfig.new()
	root.add_child(museum)
	await frames(3)
	var data:=MuseumOverview.snapshot(state,museum.business)
	check(data.owned==0 and data.displayed==0 and data.forecast_visitors==0 and data.cash==0,"Empty office has no fictitious collection or forecast income")
	check(data.halls.size()==3 and data.capacity==36,"Three halls and configured level0 capacity")
	var item:=state.collection.add(&"tang_sancai_horse",1,85,true)
	check(state.assign(&"CASE_2",item.instance_id),"Real owned item can legally display")
	data=MuseumOverview.snapshot(state,museum.business)
	check(data.identified==1 and data.displayed==1 and data.stored==0 and data.appeal>0,"Office counts actual identified displayed instance")
	museum.office_desk.interact()
	check(museum.office_panel.panel.visible and not museum.player.controls_enabled,"Physical office opens usable modal ledger")
	check(museum.office_panel.tabs.get_tab_count()>=3,"Office has overview hall and finance pages")
	museum.office_panel.close()
	check(museum.player.controls_enabled and state.cash==0,"Close restores controls without forecast cash")
	museum.queue_free()
	await frames(3)
	print("[11D1] %d checks, %d failures"%[checks,failures])
	quit(0 if failures==0 else 1)
